#logging:
#  level:
#    root: debug


spring:
  datasource:
    url: jdbc:mysql://match-mysql.cs4i16kyfber.ap-northeast-2.rds.amazonaws.com/matchdb?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: matchuser
    password: matchuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    whitelabel:
      enabled: false
